<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entrar</name>
   <tag></tag>
   <elementGuidId>440b58a9-aa4f-4ede-9d75-909cffe3d531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4247e645-3494-4c3a-b083-4cd8ec663361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>f27881c1-8b1a-4441-8521-fa0ffbbf7896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b617f368-7357-476a-a1a5-605486b7f7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Entrar
                            </value>
      <webElementGuid>d690cd3a-4385-40df-aabb-45e95888ce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cl-wrapper&quot;)/div[@class=&quot;middle-login&quot;]/div[@class=&quot;block-flat&quot;]/div[2]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;foot&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>bc40afae-ce05-447a-945e-b03d20784a4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>0163d26c-14ec-4327-a1f0-776a979b3e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cl-wrapper']/div/div/div[2]/form/div[2]/button</value>
      <webElementGuid>2dd6a74b-5759-456b-831a-1b8d1456d3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informe suas credenciais'])[1]/following::button[1]</value>
      <webElementGuid>84967890-0762-4d2b-af30-e2869b7069e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TINS Soluções Corporativas 2012-2019'])[1]/preceding::button[1]</value>
      <webElementGuid>d0db777e-b900-4d7f-b63c-1db0ed2ce646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>d0c4872e-bd68-4701-b35d-a935b6e1a926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>972d1703-022f-4780-8f7f-1412a9638808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                 Entrar
                            ' or . = '
                                 Entrar
                            ')]</value>
      <webElementGuid>37d8d66f-9a0f-45d5-98d6-382d45445075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
