<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Informe suas credenciais_senha</name>
   <tag></tag>
   <elementGuidId>92d94d57-25ee-4c02-8aab-797f8d7f41fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='senha']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;senha&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b013210e-6759-453e-b54e-6fc979dceb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>77274878-7971-4f43-be06-73c8e1c38bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>ac1d293b-909e-430e-b3f1-97685c9faf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>84a53e94-f863-4fe3-82e7-396df54915e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0253f89-2733-4db4-958e-2501d6c2a975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cl-wrapper&quot;)/div[@class=&quot;middle-login&quot;]/div[@class=&quot;block-flat&quot;]/div[2]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;form-group has-feedback&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3b30b37e-40a1-4d5f-8d78-638f23b5c522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='senha']</value>
      <webElementGuid>0c80f2ba-18f8-47d2-a6ef-69bfb6f092b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cl-wrapper']/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>c07494a0-da7d-480f-b053-de61dbccd683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>480b61a7-1463-4ff9-9d52-1ed1d331f2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Senha' and @name = 'senha']</value>
      <webElementGuid>b28beab7-10ed-42d5-9534-854b9d52a3cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
