<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Informe suas credenciais_nome_login</name>
   <tag></tag>
   <elementGuidId>095b7acc-6a9d-4d56-8858-fa1e94c4759b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nome_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nome_login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c467f3ee-26e1-4b97-8893-c11549b64891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a697c3c-aaeb-4b75-8923-ca5f91016b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>usuario@empresa</value>
      <webElementGuid>cbadeef7-6dbd-44ff-8e30-2c69b6805fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nome_login</value>
      <webElementGuid>a14e9a1f-7a7a-4e0a-9f9a-5e3630e76336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61dc7e23-474e-48a7-969c-e07727ac1b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cl-wrapper&quot;)/div[@class=&quot;middle-login&quot;]/div[@class=&quot;block-flat&quot;]/div[2]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;form-group has-feedback&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>fba02c76-419b-4a9f-88a8-d64ea56ead0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nome_login']</value>
      <webElementGuid>c2acdfee-42a5-469d-9991-47f2d19d1564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cl-wrapper']/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>c303ae52-cdb3-4ab7-92ab-ec4af36889dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9eb9ab23-4cf4-472d-94ae-70cc4b3c7c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'usuario@empresa' and @name = 'nome_login']</value>
      <webElementGuid>110b6638-f17d-4cd9-8ab4-8dc37a1532ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
